name: terraform PR Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'environments/**'
      - 'modules/**'
      - 'policies/**'

# Required for OIDC authentication to Azure

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  validate:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: setup Terraform
        uses: harshicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: Terraform format check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true
      
      - name: Terraform init
        working-directory: ./environments/dev
        run: |
          terraform init -backend-config=backend-config.hcl
      
      - name: Terraform validate
        working-directory: ./environments/dev
        run: terraform validate
      
      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.49.1/conftest_0.49.1_Linux_x86_64.tar.gz
          tar xzf conftest_0.49.1_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
      
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Plan
        id: Plan
        working-directory: ./environments/dev
        run: |
          terraform plan -out=tfplan -no-color
          terraform show -json tfplan > tfplan.json

      - name: policy check (Conftest)
        working-directory: ./environments/dev
        run: |
          conftest testtfplan.json -p ../../policies --no-color
        continue-on-error: true

